name: Docker Build
description: Build a Docker image using a configurable image name

inputs:
  image-name:
    description: Name of the Docker image
    required: true

  context:
    description: Docker build context
    required: true

runs:
  using: composite

  steps:
    - name: Build Docker image
      shell: bash
      run: docker build -t "${{ inputs.image-name }}" "${{ inputs.context }}"