name: secrets-demo

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use secret directly
        run: echo "this is my secret ${{ secrets.MY_SECRETS }}"

      - name: Use secret from environment variable
        run: echo "this is my $MY_SECRETS"
        env:
          MY_SECRETS: ${{ secrets.MY_SECRETS }}